[local]
localhost


[mongodb]
mongodb-dev.mreddy.online

[catalogue]
catalogue-dev.mreddy.online

[redis]
redis-dev.mreddy.online

[user]
user-dev.mreddy.online

[cart]
cart-dev.mreddy.online

[mysql]
mysql-dev.mreddy.online

[shipping]
shipping-dev.mreddy.online


[rabbitmq]
rabbitmq-dev.mreddy.online

[payment]
payment-dev.mreddy.online

[frontend]
frontend-dev.mreddy.online


