- name: intsall my sql
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: mysql stared 
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: set yp password
  ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ MYSQL_ROOT_PASSWORD }}"