- name: installing nodejs 
  ansible.builtin.package:
    name: nodejs
    state: present

- name: installing mysql
  ansible.builtin.package:
    name: mysqld
    state: present

-   name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

-   name: install dependencies
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app
